name: Deployment

on:
  push:
    tags:
      - v*

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    env:
      ARTIFACT_DIR: artifact
    outputs:
      sha256: ${{ steps.gen_sha256.outputs.sha256 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install system dependencies
        run: sudo apt-get install libnotify-dev
      - name: Build
        run: cargo build --release --locked
      - name: Prepare artifact
        run: |
          mkdir $ARTIFACT_DIR
          mv -f target/release/bato $ARTIFACT_DIR/
      - name: Gen sha256
        id: gen_sha256
        working-directory: ${{ env.ARTIFACT_DIR }}
        run: |
          sha256=$(sha256sum bato)
          echo "$sha256"
          echo "sha256=$sha256" >> "$GITHUB_OUTPUT"
          echo "$sha256" > bato.sha256sum
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bato
          path: ${{ env.ARTIFACT_DIR }}
          retention-days: 2

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v5
        with:
          name: bato
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bato
            bato.sha256sum

  aur-packaging:
    name: Publish AUR package
    needs: release
    runs-on: ubuntu-latest
    env:
      PKGNAME: bato
      PKGBUILD: ./.pkg/aur/PKGBUILD
      RELEASE_TAG: ${{ github.ref_name }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download sources
        run: curl -LfsSo "$PKGNAME-$RELEASE_TAG".tar.gz "https://github.com/$REPOSITORY/archive/refs/tags/$RELEASE_TAG.tar.gz"
      - name: Update PKGBUILD
        run: ./.pkg/aur/update.sh
      - name: Show PKGBUILD
        run: cat "$PKGBUILD"
      - name: Publish
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: ${{ env.PKG_NAME }}
          pkgbuild: ${{ env.PKGBUILD }}
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
          commit_message: ${{ github.ref_name }}
