name: Rust

on:
  push:
    tags:
      - v* # Push events to v* tags

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libnotify
      run: sudo apt-get install libnotify-dev
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo build --release --locked
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/bato
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
