name: Test

on:
  workflow_call:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: Install libnotify
        run: sudo apt-get install libnotify-dev
      - name: Lint
        run: cargo clippy
      - name: Check
        run: cargo check
